-- Create penalty table for user account penalties
CREATE TABLE penalty (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  user_role VARCHAR(50) NOT NULL, -- Changed from role_enum to VARCHAR for compatibility
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  admin_id BIGINT NOT NULL,
  penaltytime TIMESTAMP NOT NULL,
  created TIMESTAMPTZ DEFAULT NOW(),
  verified TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (admin_id) REFERENCES admin(user_id)
);

-- Create index for faster lookups
CREATE INDEX idx_penalty_user_id ON penalty(user_id);
CREATE INDEX idx_penalty_penaltytime ON penalty(penaltytime);

-- Add comments for documentation
COMMENT ON TABLE penalty IS 'Stores penalty information for users who violate platform rules';
COMMENT ON COLUMN penalty.report_id IS 'Unique identifier for the penalty record';
COMMENT ON COLUMN penalty.user_id IS 'ID of the penalized user';
COMMENT ON COLUMN penalty.user_role IS 'Role of the penalized user (buyer, seller, bat, admin, etc.)';
COMMENT ON COLUMN penalty.title IS 'Brief title of the penalty';
COMMENT ON COLUMN penalty.description IS 'Detailed description of the penalty reason';
COMMENT ON COLUMN penalty.admin_id IS 'ID of the admin who issued the penalty';
COMMENT ON COLUMN penalty.penaltytime IS 'Timestamp when the penalty expires';
COMMENT ON COLUMN penalty.created IS 'When the penalty was created';
COMMENT ON COLUMN penalty.verified IS 'When the penalty was verified/confirmed';
